### ISSUE TITLE
The exception message 'Unable to load the public suffix list rules for %s' is ambiguous

### ISSUE THREAD

**Issue by Ascerta** [thephpleague/uri-hostname-parser#6]
## Issue summary

getRules() in ICANNSectionManager throws an exception with the message 'Unable to load the public suffix list rules for %s'. The exception is thrown either if there is a problem retrieving the content via the httpClient or if there is a problem setting the cache. The exception message makes it appear as if the problem is is always with the httpclient.

Should the exception message be expanded to be more descriptive or an additional exception raised in the case of a cache fault?

**Comment by nyamsprod** [comment]
@Ascerta 

- if an error occurs with the http client, a `League\Uri\PublicSuffix\HttpClientException` is thrown;
- if an error occurs with the cache client, a `League\Uri\PublicSuffix\CacheException` is thrown;

For anything else (parsing the data is not possible, for instance) then a `League\Uri\PublicSuffix\Exception` is thrown.  So depending on the exception thrown you can already guess where the issue is or I'm missing something 🤔

**Comment by Ascerta** [comment]
@nyamsprod 
When `refreshRules()` returns false `ICANNSectionManager->getRules()` throws the general exception
`Exception(sprintf('Unable to load the public suffix list rules for %s', $source_url))`

`refreshRules()` can fail either if there is an network issue or an issue writing the cache to disk but it doesn't throw an exception or have detailed returned type.

As the cache will, by default write to the vendor directory the exception message doesn't make it clear that the fault could be a file permissions problem or a network issue.

**Comment by nyamsprod** [comment]
> When refreshRules() returns false ICANNSectionManager->getRules() throws the general exception
Exception(sprintf('Unable to load the public suffix list rules for %s', $source_url))

Which is normal because if it returns false it means that the value could not be cached or that the cache is invalid and that refresh could not parse correctly or saved the data to the cache so it is a system error. The manager exit because it can not perform what it has to do.

> RefreshRules() can fail either if there is an network issue

will trigger a HttpClientException

> or an issue writing the cache to disk

will trigger a CacheException on cache settings or will return false.  
The fact that you can not write/save the cache version is not consider exceptional in PSR-6/16. A fail cache should not block your code in most cases.

> As the cache will, by default write to the vendor directory the exception message doesn't make it clear that the fault could be a file permissions problem or a network issue.

True, but again this was the way PDP v3.0 use to work and this package is only a patched version to allow it to work on PHP7+ correctly. It was not meant to solve other issues alas.
